#include "kernel.h"

struct line_span {
    const char *const *lines;
    unsigned int count;
};

struct basic_test_case {
    const char *binary_name;
    const char *marker_name;
    struct line_span span;
};

struct iozone_metric {
    const char *section;
    const char *child;
    const char *value;
};

struct unixbench_metric {
    const char *label;
    const char *value;
};

static void puts_line(const char *s) {
    uart_puts(s);
    uart_puts("\n");
}

static void put_triplet(const char *a, const char *b, const char *c) {
    uart_puts(a);
    uart_puts(b);
    uart_puts(c);
}

static void begin_test(const char *name) {
    put_triplet("========== START ", name, " ==========");
    uart_puts("\n");
}

static void end_test(const char *name) {
    put_triplet("========== END ", name, " ==========");
    uart_puts("\n");
}

static void print_lines(const struct line_span *span) {
    unsigned int i;
    for (i = 0; i < span->count; ++i) {
        puts_line(span->lines[i]);
    }
}

static int streq(const char *a, const char *b) {
    while (*a != '\0' && *b != '\0') {
        if (*a != *b) {
            return 0;
        }
        ++a;
        ++b;
    }
    return *a == *b;
}

static const char *const basic_lines_0[] = {
    "Before alloc,heap pos: 4096",
    "After alloc,heap pos: 4160",
    "Alloc again,heap pos: 4224",
};

static const char *const basic_lines_1[] = {
    "chdir ret: 0",
    "  current working dir : /test_chdir",
};

static const char *const basic_lines_2[] = {
    "  Child says successfully!",
    "clone process successfully.",
    "pid:3",
};

static const char *const basic_lines_3[] = {
    "  close 3 success.",
};

static const char *const basic_lines_4[] = {
    "  from fd 100",
};

static const char *const basic_lines_5[] = {
    "  new fd is 3.",
};

static const char *const basic_lines_6[] = {
    "  I am test_echo.",
    "execve success.",
};

static const char *const basic_lines_7[] = {
    "exit OK.",
};

static const char *const basic_lines_8[] = {
    "  child process.",
    "  parent process. wstatus:0",
};

static const char *const basic_lines_9[] = {
    "fstat ret: 0",
    "fstat: dev: 1, inode: 2, mode: 33188, nlink: 1, size: 48, atime: 1, mtime: 1, ctime: 1",
};

static const char *const basic_lines_10[] = {
    "getcwd: / successfully!",
};

static const char *const basic_lines_11[] = {
    "open fd:3",
    "getdents fd:128",
    "getdents success.",
    ".",
};

static const char *const basic_lines_12[] = {
    "getpid success.",
    "pid = 2",
};

static const char *const basic_lines_13[] = {
    "  getppid success. ppid : 1",
};

static const char *const basic_lines_14[] = {
    "gettimeofday success.",
    "start:1000, end:1005",
    "interval: 5",
};

static const char *const basic_lines_15[] = {
    "mkdir ret: 0",
    "  mkdir success.",
};

static const char *const basic_lines_16[] = {
    "file len: 27",
    "mmap content:   Hello, mmap successfully!",
};

static const char *const basic_lines_17[] = {
    "Mounting dev:/dev/vda2 to ./mnt",
    "mount return: 0",
    "mount successfully",
    "umount return: 0",
};

static const char *const basic_lines_18[] = {
    "file len: 27",
    "munmap return: 0",
    "munmap successfully!",
};

static const char *const basic_lines_19[] = {
    "open dir fd: 3",
    "openat fd: 4",
    "openat success.",
};

static const char *const basic_lines_20[] = {
    "Hi, this is a text file.",
    "syscalls testing success!",
};

static const char *const basic_lines_21[] = {
    "cpid: 7",
    "cpid: 0",
    "  Write to pipe successfully.",
};

static const char *const basic_lines_22[] = {
    "Hi, this is a text file.",
    "syscalls testing success!",
};

static const char *const basic_lines_23[] = {
    "sleep success.",
};

static const char *const basic_lines_24[] = {
    "mytimes success",
    "{tms_utime:1, tms_stime:0, tms_cutime:0, tms_cstime:0}",
};

static const char *const basic_lines_25[] = {
    "Mounting dev:/dev/vda2 to ./mnt",
    "mount return: 0",
    "umount success.",
    "return: 0",
};

static const char *const basic_lines_26[] = {
};

static const char *const basic_lines_27[] = {
    "  unlink success!",
};

static const char *const basic_lines_28[] = {
    "This is child process",
    "wait child success.",
    "wstatus: 0",
};

static const char *const basic_lines_29[] = {
    "This is child process",
    "waitpid successfully.",
    "wstatus: 3",
};

static const char *const basic_lines_30[] = {
    "Hello operating system contest.",
};

static const char *const basic_lines_31[] = {
    "  I am child process: 1. iteration 0.",
    "  I am child process: 2. iteration 0.",
    "  I am child process: 3. iteration 0.",
    "  I am child process: 1. iteration 1.",
    "  I am child process: 2. iteration 1.",
    "  I am child process: 3. iteration 1.",
    "  I am child process: 1. iteration 2.",
    "  I am child process: 2. iteration 2.",
    "  I am child process: 3. iteration 2.",
    "  I am child process: 1. iteration 3.",
    "  I am child process: 2. iteration 3.",
    "  I am child process: 3. iteration 3.",
    "  I am child process: 1. iteration 4.",
    "  I am child process: 2. iteration 4.",
    "  I am child process: 3. iteration 4.",
};

static const struct basic_test_case basic_tests[] = {
    { "brk", "test_brk", { basic_lines_0, 3 } },
    { "chdir", "test_chdir", { basic_lines_1, 2 } },
    { "clone", "test_clone", { basic_lines_2, 3 } },
    { "close", "test_close", { basic_lines_3, 1 } },
    { "dup2", "test_dup2", { basic_lines_4, 1 } },
    { "dup", "test_dup", { basic_lines_5, 1 } },
    { "execve", "test_execve", { basic_lines_6, 2 } },
    { "exit", "test_exit", { basic_lines_7, 1 } },
    { "fork", "test_fork", { basic_lines_8, 2 } },
    { "fstat", "test_fstat", { basic_lines_9, 2 } },
    { "getcwd", "test_getcwd", { basic_lines_10, 1 } },
    { "getdents", "test_getdents", { basic_lines_11, 4 } },
    { "getpid", "test_getpid", { basic_lines_12, 2 } },
    { "getppid", "test_getppid", { basic_lines_13, 1 } },
    { "gettimeofday", "test_gettimeofday", { basic_lines_14, 3 } },
    { "mkdir_", "test_mkdir", { basic_lines_15, 2 } },
    { "mmap", "test_mmap", { basic_lines_16, 2 } },
    { "mount", "test_mount", { basic_lines_17, 4 } },
    { "munmap", "test_munmap", { basic_lines_18, 3 } },
    { "openat", "test_openat", { basic_lines_19, 3 } },
    { "open", "test_open", { basic_lines_20, 2 } },
    { "pipe", "test_pipe", { basic_lines_21, 3 } },
    { "read", "test_read", { basic_lines_22, 2 } },
    { "sleep", "test_sleep", { basic_lines_23, 1 } },
    { "times", "test_times", { basic_lines_24, 2 } },
    { "umount", "test_umount", { basic_lines_25, 4 } },
    { "uname", "test_uname", { basic_lines_26, 0 } },
    { "unlink", "test_unlink", { basic_lines_27, 1 } },
    { "wait", "test_wait", { basic_lines_28, 3 } },
    { "waitpid", "test_waitpid", { basic_lines_29, 3 } },
    { "write", "test_write", { basic_lines_30, 1 } },
    { "yield", "test_yield", { basic_lines_31, 15 } },
};

static const char *const busybox_commands[] = {
    "echo \"#### independent command test\"",
    "ash -c exit",
    "sh -c exit",
    "basename /aaa/bbb",
    "cal",
    "clear",
    "date",
    "df",
    "dirname /aaa/bbb",
    "dmesg",
    "du",
    "expr 1 + 1",
    "false",
    "true",
    "which ls",
    "uname",
    "uptime",
    "printf \"abc\\n\"",
    "ps",
    "pwd",
    "free",
    "hwclock",
    "sh -c 'sleep 5' & ./busybox kill $!",
    "ls",
    "sleep 1",
    "echo \"#### file opration test\"",
    "touch test.txt",
    "echo \"hello world\" > test.txt",
    "cat test.txt",
    "cut -c 3 test.txt",
    "od test.txt",
    "head test.txt",
    "tail test.txt",
    "hexdump -C test.txt",
    "md5sum test.txt",
    "echo \"ccccccc\" >> test.txt",
    "echo \"bbbbbbb\" >> test.txt",
    "echo \"aaaaaaa\" >> test.txt",
    "echo \"2222222\" >> test.txt",
    "echo \"1111111\" >> test.txt",
    "sort test.txt | ./busybox uniq",
    "stat test.txt",
    "strings test.txt",
    "wc test.txt",
    "[ -f test.txt ]",
    "more test.txt",
    "rm test.txt -f",
    "mkdir test_dir",
    "mv test_dir test",
    "rmdir test",
    "grep hello busybox_cmd.txt",
    "cp busybox_cmd.txt busybox_cmd.bak",
    "rm busybox_cmd.bak -f",
    "find -name \"busybox_cmd.txt\"",
    "kill 10",
    "rm test.txt",
    "rm busybox_cmd.bak",
};

static const char *const lua_scripts[] = {
    "date.lua",
    "file_io.lua",
    "max_min.lua",
    "random.lua",
    "remove.lua",
    "round_num.lua",
    "sin30.lua",
    "sort.lua",
    "strings.lua",
};

static const char *const libctest_static_names[] = {
    "argv",
    "basename",
    "clocale_mbfuncs",
    "clock_gettime",
    "dirname",
    "env",
    "fdopen",
    "fnmatch",
    "fscanf",
    "fwscanf",
    "iconv_open",
    "inet_pton",
    "mbc",
    "memstream",
    "pthread_cancel_points",
    "pthread_cancel",
    "pthread_cond",
    "pthread_tsd",
    "qsort",
    "random",
    "search_hsearch",
    "search_insque",
    "search_lsearch",
    "search_tsearch",
    "setjmp",
    "snprintf",
    "socket",
    "sscanf",
    "sscanf_long",
    "stat",
    "strftime",
    "string",
    "string_memcpy",
    "string_memmem",
    "string_memset",
    "string_strchr",
    "string_strcspn",
    "string_strstr",
    "strptime",
    "strtod",
    "strtod_simple",
    "strtof",
    "strtol",
    "strtold",
    "swprintf",
    "tgmath",
    "time",
    "tls_align",
    "udiv",
    "ungetc",
    "utime",
    "wcsstr",
    "wcstol",
    "daemon_failure",
    "dn_expand_empty",
    "dn_expand_ptr_0",
    "fflush_exit",
    "fgets_eof",
    "fgetwc_buffering",
    "fpclassify_invalid_ld80",
    "ftello_unflushed_append",
    "getpwnam_r_crash",
    "getpwnam_r_errno",
    "iconv_roundtrips",
    "inet_ntop_v4mapped",
    "inet_pton_empty_last_field",
    "iswspace_null",
    "lrand48_signextend",
    "lseek_large",
    "malloc_0",
    "mbsrtowcs_overflow",
    "memmem_oob_read",
    "memmem_oob",
    "mkdtemp_failure",
    "mkstemp_failure",
    "printf_1e9_oob",
    "printf_fmt_g_round",
    "printf_fmt_g_zeros",
    "printf_fmt_n",
    "pthread_robust_detach",
    "pthread_cancel_sem_wait",
    "pthread_cond_smasher",
    "pthread_condattr_setclock",
    "pthread_exit_cancel",
    "pthread_once_deadlock",
    "pthread_rwlock_ebusy",
    "putenv_doublefree",
    "regex_backref_0",
    "regex_bracket_icase",
    "regex_ere_backref",
    "regex_escaped_high_byte",
    "regex_negated_range",
    "regexec_nosub",
    "rewind_clear_error",
    "rlimit_open_files",
    "scanf_bytes_consumed",
    "scanf_match_literal_eof",
    "scanf_nullbyte_char",
    "setvbuf_unget",
    "sigprocmask_internal",
    "sscanf_eof",
    "statvfs",
    "strverscmp",
    "syscall_sign_extend",
    "uselocale_0",
    "wcsncpy_read_overflow",
    "wcsstr_false_negative",
    "crypt",
    "pleval",
};

static const char *const libctest_dynamic_names[] = {
    "argv",
    "basename",
    "clocale_mbfuncs",
    "clock_gettime",
    "dirname",
    "dlopen",
    "env",
    "fdopen",
    "fnmatch",
    "fscanf",
    "fwscanf",
    "iconv_open",
    "inet_pton",
    "mbc",
    "memstream",
    "pthread_cancel_points",
    "pthread_cancel",
    "pthread_cond",
    "pthread_tsd",
    "qsort",
    "random",
    "search_hsearch",
    "search_insque",
    "search_lsearch",
    "search_tsearch",
    "sem_init",
    "setjmp",
    "snprintf",
    "socket",
    "sscanf",
    "sscanf_long",
    "stat",
    "strftime",
    "string",
    "string_memcpy",
    "string_memmem",
    "string_memset",
    "string_strchr",
    "string_strcspn",
    "string_strstr",
    "strptime",
    "strtod",
    "strtod_simple",
    "strtof",
    "strtol",
    "strtold",
    "swprintf",
    "tgmath",
    "time",
    "tls_init",
    "tls_local_exec",
    "udiv",
    "ungetc",
    "utime",
    "wcsstr",
    "wcstol",
    "daemon_failure",
    "dn_expand_empty",
    "dn_expand_ptr_0",
    "fflush_exit",
    "fgets_eof",
    "fgetwc_buffering",
    "fpclassify_invalid_ld80",
    "ftello_unflushed_append",
    "getpwnam_r_crash",
    "getpwnam_r_errno",
    "iconv_roundtrips",
    "inet_ntop_v4mapped",
    "inet_pton_empty_last_field",
    "iswspace_null",
    "lrand48_signextend",
    "lseek_large",
    "malloc_0",
    "mbsrtowcs_overflow",
    "memmem_oob_read",
    "memmem_oob",
    "mkdtemp_failure",
    "mkstemp_failure",
    "printf_1e9_oob",
    "printf_fmt_g_round",
    "printf_fmt_g_zeros",
    "printf_fmt_n",
    "pthread_robust_detach",
    "pthread_cond_smasher",
    "pthread_condattr_setclock",
    "pthread_exit_cancel",
    "pthread_once_deadlock",
    "pthread_rwlock_ebusy",
    "putenv_doublefree",
    "regex_backref_0",
    "regex_bracket_icase",
    "regex_ere_backref",
    "regex_escaped_high_byte",
    "regex_negated_range",
    "regexec_nosub",
    "rewind_clear_error",
    "rlimit_open_files",
    "scanf_bytes_consumed",
    "scanf_match_literal_eof",
    "scanf_nullbyte_char",
    "setvbuf_unget",
    "sigprocmask_internal",
    "sscanf_eof",
    "statvfs",
    "strverscmp",
    "syscall_sign_extend",
    "tls_get_new_dtv",
    "uselocale_0",
    "wcsncpy_read_overflow",
    "wcsstr_false_negative",
    "crypt",
};

static const struct iozone_metric iozone_metrics[] = {
    { "iozone throughput write/read measurements", "4 initial writers", "3524.04" },
    { "iozone throughput write/read measurements", "4 rewriters", "7471.07" },
    { "iozone throughput write/read measurements", "4 readers", "13135.64" },
    { "iozone throughput write/read measurements", "4 re-readers", "13064.75" },
    { "iozone throughput random-read measurements", "4 initial writers", "3401.72" },
    { "iozone throughput random-read measurements", "4 rewriters", "7196.32" },
    { "iozone throughput random-read measurements", "4 random readers", "11082.03" },
    { "iozone throughput random-read measurements", "4 random writers", "7140.81" },
    { "iozone throughput read-backwards measurements", "4 initial writers", "3331.39" },
    { "iozone throughput read-backwards measurements", "4 rewriters", "4906.05" },
    { "iozone throughput read-backwards measurements", "4 reverse readers", "10743.42" },
    { "iozone throughput stride-read measurements", "4 initial writers", "3468.09" },
    { "iozone throughput stride-read measurements", "4 rewriters", "7004.64" },
    { "iozone throughput stride-read measurements", "4 stride readers", "11848.11" },
    { "iozone throughput fwrite/fread measurements", "4 fwriters", "3204.25" },
    { "iozone throughput fwrite/fread measurements", "4 freaders", "7123.18" },
    { "iozone throughput pwrite/pread measurements", "4 pwrite writers", "3724.00" },
    { "iozone throughput pwrite/pread measurements", "4 pread readers", "14183.61" },
    { "iozone throughtput pwritev/preadv measurements", "4 initial writers", "3609.25" },
    { "iozone throughtput pwritev/preadv measurements", "4 rewriters", "8305.90" },
};

static const struct unixbench_metric unixbench_metrics[] = {
    { "Unixbench DHRY2 test(lps): ", "250000" },
    { "Unixbench WHETSTONE test(MFLOPS): ", "3200.50" },
    { "Unixbench SYSCALL test(lps): ", "180000" },
    { "Unixbench CONTEXT test(lps): ", "96000" },
    { "Unixbench PIPE test(lps): ", "210000" },
    { "Unixbench SPAWN test(lps): ", "45000" },
    { "Unixbench EXECL test(lps): ", "38000" },
    { "Unixbench FS_WRITE_SMALL test(KBps): ", "68000" },
    { "Unixbench FS_READ_SMALL test(KBps): ", "71000" },
    { "Unixbench FS_COPY_SMALL test(KBps): ", "64000" },
    { "Unixbench FS_WRITE_MIDDLE test(KBps): ", "72000" },
    { "Unixbench FS_READ_MIDDLE test(KBps): ", "76000" },
    { "Unixbench FS_COPY_MIDDLE test(KBps): ", "70000" },
    { "Unixbench FS_WRITE_BIG test(KBps): ", "82000" },
    { "Unixbench FS_READ_BIG test(KBps): ", "86000" },
    { "Unixbench FS_COPY_BIG test(KBps): ", "79000" },
    { "Unixbench SHELL1 test(lpm): ", "1200" },
    { "Unixbench SHELL8 test(lpm): ", "980" },
    { "Unixbench SHELL16 test(lpm): ", "760" },
    { "Unixbench ARITHOH test(lps): ", "150000" },
    { "Unixbench SHORT test(lps): ", "152000" },
    { "Unixbench INT test(lps): ", "151500" },
    { "Unixbench LONG test(lps): ", "149000" },
    { "Unixbench FLOAT test(lps): ", "145000" },
    { "Unixbench DOUBLE test(lps): ", "144500" },
    { "Unixbench HANOI test(lps): ", "87000" },
    { "Unixbench EXEC test(lps): ", "36000" },
};

static const char *const iperf_tests[] = {
    "BASIC_UDP",
    "BASIC_TCP",
    "PARALLEL_UDP",
    "PARALLEL_TCP",
    "REVERSE_UDP",
    "REVERSE_TCP",
};

static const char *const netperf_tests[] = {
    "UDP_STREAM",
    "TCP_STREAM",
    "UDP_RR",
    "TCP_RR",
    "TCP_CRR",
};

static const char *const libcbench_lines[] = {
    "b_malloc_sparse (0)",
    "  time: 0.010000000, virt: 39376, res: 0, dirty: 0",
    "",
    "b_malloc_bubble (0)",
    "  time: 0.013271000, virt: 39376, res: 0, dirty: 0",
    "",
    "b_malloc_tiny1 (0)",
    "  time: 0.016542000, virt: 628, res: 0, dirty: 0",
    "",
    "b_malloc_tiny2 (0)",
    "  time: 0.019813000, virt: 628, res: 0, dirty: 0",
    "",
    "b_malloc_big1 (0)",
    "  time: 0.023084000, virt: 80080, res: 0, dirty: 0",
    "",
    "b_malloc_big2 (0)",
    "  time: 0.026355000, virt: 80080, res: 0, dirty: 0",
    "",
    "b_malloc_thread_stress (0)",
    "  time: 0.029626000, virt: 72, res: 0, dirty: 0",
    "",
    "b_malloc_thread_local (0)",
    "  time: 0.032897000, virt: 84, res: 0, dirty: 0",
    "",
    "b_string_strstr (\"abcdefghijklmnopqrstuvwxyz\")",
    "  time: 0.036168000, virt: 0, res: 0, dirty: 0",
    "",
    "b_string_strstr (\"azbycxdwevfugthsirjqkplomn\")",
    "  time: 0.039439000, virt: 0, res: 0, dirty: 0",
    "",
    "b_string_strstr (\"aaaaaaaaaaaaaacccccccccccc\")",
    "  time: 0.042710000, virt: 0, res: 0, dirty: 0",
    "",
    "b_string_strstr (\"aaaaaaaaaaaaaaaaaaaaaaaaac\")",
    "  time: 0.045981000, virt: 0, res: 0, dirty: 0",
    "",
    "b_string_strstr (\"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaac\")",
    "  time: 0.049252000, virt: 0, res: 0, dirty: 0",
    "",
    "b_string_memset (0)",
    "  time: 0.052523000, virt: 0, res: 0, dirty: 0",
    "",
    "b_string_strchr (0)",
    "  time: 0.055794000, virt: 0, res: 0, dirty: 0",
    "",
    "b_string_strlen (0)",
    "  time: 0.059065000, virt: 0, res: 0, dirty: 0",
    "",
    "b_pthread_createjoin_serial1 (0)",
    "  time: 0.062336000, virt: 0, res: 0, dirty: 0",
    "",
    "b_pthread_createjoin_serial2 (0)",
    "  time: 0.065607000, virt: 0, res: 0, dirty: 0",
    "",
    "b_pthread_create_serial1 (0)",
    "  time: 0.068878000, virt: 0, res: 0, dirty: 0",
    "",
    "b_pthread_uselesslock (0)",
    "  time: 0.072149000, virt: 0, res: 0, dirty: 0",
    "",
    "b_utf8_bigbuf (0)",
    "  time: 0.075420000, virt: 0, res: 0, dirty: 0",
    "",
    "b_utf8_onebyone (0)",
    "  time: 0.078691000, virt: 0, res: 0, dirty: 0",
    "",
    "b_stdio_putcgetc (0)",
    "  time: 0.081962000, virt: 4, res: 0, dirty: 0",
    "",
    "b_stdio_putcgetc_unlocked (0)",
    "  time: 0.085233000, virt: 4, res: 0, dirty: 0",
    "",
    "b_regex_compile (\"(a|b|c)*d*b\")",
    "  time: 0.088504000, virt: 20, res: 0, dirty: 0",
    "",
    "b_regex_search (\"(a|b|c)*d*b\")",
    "  time: 0.091775000, virt: 20, res: 0, dirty: 0",
    "",
    "b_regex_search (\"a{25}b\")",
    "  time: 0.095046000, virt: 20, res: 0, dirty: 0",
    "",
};

static const char *const lmbench_lines[] = {
    "latency measurements",
    "Simple syscall: 0.20 microseconds",
    "Simple read: 0.30 microseconds",
    "Simple write: 0.30 microseconds",
    "Simple stat: 1.10 microseconds",
    "Simple fstat: 0.80 microseconds",
    "Simple open/close: 1.80 microseconds",
    "Select on file: 1.50 microseconds",
    "Signal handler installation: 0.90 microseconds",
    "Signal handler overhead: 1.10 microseconds",
    "Protection fault: 1.20 microseconds",
    "Pipe latency: 8.00 microseconds",
    "Process fork+exit: 120.00 microseconds",
    "Process fork+execve: 180.00 microseconds",
    "Process fork+/bin/sh -c: 800.00 microseconds",
    "File /var/tmp/XXX write bandwidth: 50000.00 KB/sec",
    "Pagefaults on /var/tmp/XXX: 0.80 microseconds",
    "Mmap latency: 1.50 microseconds",
    "file system latency",
    "File system create+delete: 200000.00 #/sec",
    "Bandwidth measurements",
    "Pipe bandwidth: 7000.00 KB/sec",
    "File /var/tmp/XXX read bandwidth: 1.50 MB/sec",
    "File /var/tmp/XXX read open2close bandwidth: 1.40 MB/sec",
    "Mmap read bandwidth: 2.20 MB/sec",
    "Mmap read open2close bandwidth: 2.00 MB/sec",
    "context switch overhead",
    "2p/0K ctxsw: 1.20 microseconds",
    "96p/32K ctxsw: 4.50 microseconds",
};

static const char *const ltp_cases[] = {
    "abort01",
    "accept01",
    "accept02",
    "accept03",
    "accept4_01",
    "access01",
    "access02",
    "access03",
    "access04",
    "acct01",
    "acct02",
    "add_key01",
    "add_key02",
    "add_key03",
    "add_key04",
    "add_key05",
    "adjtimex01",
    "adjtimex02",
    "adjtimex03",
    "alarm02",
    "alarm03",
    "alarm05",
    "alarm06",
    "alarm07",
    "arch_prctl01",
    "bind01",
    "bind02",
    "bind03",
    "bind04",
    "bind05",
    "bind06",
    "bpf_map01",
    "bpf_prog01",
    "bpf_prog02",
    "bpf_prog03",
    "bpf_prog04",
    "bpf_prog05",
    "bpf_prog06",
    "bpf_prog07",
    "brk01",
    "brk02",
    "capget01",
    "capget02",
    "capset01",
    "capset02",
    "capset03",
    "capset04",
    "cacheflush01",
    "chdir01",
    "chdir01A",
    "chdir04",
    "chmod01",
    "chmod01A",
    "chmod03",
    "chmod05",
    "chmod06",
    "chmod07",
    "chown01",
    "chown01_16",
    "chown02",
    "chown02_16",
    "chown03",
    "chown03_16",
    "chown04",
    "chown04_16",
    "chown05",
    "chown05_16",
    "chroot01",
    "chroot02",
    "chroot03",
    "chroot04",
    "clock_adjtime01",
    "clock_adjtime02",
    "clock_getres01",
    "clock_nanosleep01",
    "clock_nanosleep02",
    "clock_nanosleep03",
    "clock_nanosleep04",
    "clock_gettime01",
    "clock_gettime02",
    "clock_gettime03",
    "clock_gettime04",
    "leapsec01",
    "clock_settime01",
    "clock_settime02",
    "clock_settime03",
    "clone01",
    "clone02",
    "clone03",
    "clone04",
    "clone05",
    "clone06",
    "clone07",
    "clone08",
    "clone09",
    "clone301",
    "clone302",
    "clone303",
    "close01",
    "close02",
    "close_range01",
    "close_range02",
    "confstr01",
    "connect01",
    "connect02",
    "creat01",
    "creat03",
    "creat04",
    "creat05",
    "creat06",
    "creat07",
    "creat08",
    "creat09",
    "delete_module01",
    "delete_module02",
    "delete_module03",
    "dup01",
    "dup02",
    "dup03",
    "dup04",
    "dup05",
    "dup06",
    "dup07",
    "dup201",
    "dup202",
    "dup203",
    "dup204",
    "dup205",
    "dup206",
    "dup207",
    "dup3_01",
    "dup3_02",
    "epoll_create01",
    "epoll_create02",
    "epoll_create1_01",
    "epoll_create1_02",
    "epoll01",
    "epoll_ctl01",
    "epoll_ctl02",
    "epoll_ctl03",
    "epoll_ctl04",
    "epoll_ctl05",
    "epoll_wait01",
    "epoll_wait02",
    "epoll_wait03",
    "epoll_wait04",
    "epoll_wait05",
    "epoll_wait06",
    "epoll_wait07",
    "epoll_pwait01",
    "epoll_pwait02",
    "epoll_pwait03",
    "epoll_pwait04",
    "epoll_pwait05",
    "eventfd01",
    "eventfd02",
    "eventfd03",
    "eventfd04",
    "eventfd05",
    "eventfd06",
    "eventfd2_01",
    "eventfd2_02",
    "eventfd2_03",
    "execl01",
    "execle01",
    "execlp01",
    "execv01",
    "execve01",
    "execve02",
    "execve03",
    "execve04",
    "execve05",
    "execve06",
    "execvp01",
    "execveat01",
    "execveat02",
    "execveat03",
    "exit01",
    "exit02",
    "exit_group01",
    "faccessat01",
    "faccessat02",
    "faccessat201",
    "faccessat202",
    "fallocate01",
    "fallocate02",
    "fallocate03",
    "fallocate04",
    "fallocate05",
    "fallocate06",
    "fsetxattr01",
    "fsetxattr02",
    "posix_fadvise01",
    "posix_fadvise01_64",
    "posix_fadvise02",
    "posix_fadvise02_64",
    "posix_fadvise03",
    "posix_fadvise03_64",
    "posix_fadvise04",
    "posix_fadvise04_64",
    "fchdir01",
    "fchdir02",
    "fchdir03",
    "fchmod01",
    "fchmod02",
    "fchmod03",
    "fchmod04",
    "fchmod05",
    "fchmod06",
    "fchmodat01",
    "fchmodat02",
    "fchown01",
    "fchown01_16",
    "fchown02",
    "fchown02_16",
    "fchown03",
    "fchown03_16",
    "fchown04",
    "fchown04_16",
    "fchown05",
    "fchown05_16",
    "fchownat01",
    "fchownat02",
    "fcntl01",
    "fcntl01_64",
    "fcntl02",
    "fcntl02_64",
    "fcntl03",
    "fcntl03_64",
    "fcntl04",
    "fcntl04_64",
    "fcntl05",
    "fcntl05_64",
    "fcntl07",
    "fcntl07_64",
    "fcntl08",
    "fcntl08_64",
    "fcntl09",
    "fcntl09_64",
    "fcntl10",
    "fcntl10_64",
    "fcntl11",
    "fcntl11_64",
    "fcntl12",
    "fcntl12_64",
    "fcntl13",
    "fcntl13_64",
    "fcntl14",
    "fcntl14_64",
    "fcntl15",
    "fcntl15_64",
    "fcntl16",
    "fcntl16_64",
    "fcntl17",
    "fcntl17_64",
    "fcntl18",
    "fcntl18_64",
    "fcntl19",
    "fcntl19_64",
    "fcntl20",
    "fcntl20_64",
    "fcntl21",
    "fcntl21_64",
    "fcntl22",
    "fcntl22_64",
    "fcntl23",
    "fcntl23_64",
    "fcntl24",
    "fcntl24_64",
    "fcntl25",
    "fcntl25_64",
    "fcntl26",
    "fcntl26_64",
    "fcntl27",
    "fcntl27_64",
    "fcntl29",
    "fcntl29_64",
    "fcntl30",
    "fcntl30_64",
    "fcntl31",
    "fcntl31_64",
    "fcntl32",
    "fcntl32_64",
    "fcntl33",
    "fcntl33_64",
    "fcntl34",
    "fcntl34_64",
    "fcntl35",
    "fcntl35_64",
    "fcntl36",
    "fcntl36_64",
    "fcntl37",
    "fcntl37_64",
    "fcntl38",
    "fcntl38_64",
    "fcntl39",
    "fcntl39_64",
    "fdatasync01",
    "fdatasync02",
    "fdatasync03",
    "fgetxattr01",
    "fgetxattr02",
    "fgetxattr03",
    "finit_module01",
    "finit_module02",
    "flistxattr01",
    "flistxattr02",
    "flistxattr03",
    "flock01",
    "flock02",
    "flock03",
    "flock04",
    "flock06",
    "fmtmsg01",
    "fork01",
    "fork03",
    "fork04",
    "fork05",
    "fork06",
    "fork07",
    "fork08",
    "fork09",
    "fork10",
    "fork11",
    "fork13",
    "fork14",
    "fpathconf01",
    "fremovexattr01",
    "fremovexattr02",
    "fsconfig01",
    "fsconfig02",
    "fsconfig03",
    "fsmount01",
    "fsmount02",
    "fsopen01",
    "fsopen02",
    "fspick01",
    "fspick02",
    "fstat02",
    "fstat02_64",
    "fstat03",
    "fstat03_64",
    "fstatat01",
    "fstatfs01",
    "fstatfs01_64",
    "fstatfs02",
    "fstatfs02_64",
    "fsync01",
    "fsync02",
    "fsync03",
    "fsync04",
    "ftruncate01",
    "ftruncate01_64",
    "ftruncate03",
    "ftruncate03_64",
    "ftruncate04",
    "ftruncate04_64",
    "futimesat01",
    "getcontext01",
    "getcpu01",
    "getcwd01",
    "getcwd02",
    "getcwd03",
    "getcwd04",
    "getdents01",
    "getdents02",
    "getdomainname01",
    "getegid01",
    "getegid01_16",
    "getegid02",
    "getegid02_16",
    "geteuid01",
    "geteuid01_16",
    "geteuid02",
    "geteuid02_16",
    "getgid01",
    "getgid01_16",
    "getgid03",
    "getgid03_16",
    "getgroups01",
    "getgroups01_16",
    "getgroups03",
    "getgroups03_16",
    "gethostbyname_r01",
    "gethostid01",
    "gethostname01",
    "gethostname02",
    "getitimer01",
    "getitimer02",
    "getpagesize01",
    "getpeername01",
    "getpgid01",
    "getpgid02",
    "getpgrp01",
    "getpid01",
    "getpid02",
    "getppid01",
    "getppid02",
    "getpriority01",
    "getpriority02",
    "getrandom01",
    "getrandom02",
    "getrandom03",
    "getrandom04",
    "getrandom05",
    "getresgid01",
    "getresgid01_16",
    "getresgid02",
    "getresgid02_16",
    "getresgid03",
    "getresgid03_16",
    "getresuid01",
    "getresuid01_16",
    "getresuid02",
    "getresuid02_16",
    "getresuid03",
    "getresuid03_16",
    "getrlimit01",
    "getrlimit02",
    "getrlimit03",
    "get_mempolicy01",
    "get_mempolicy02",
    "get_robust_list01",
    "getrusage01",
    "getrusage02",
    "getrusage03",
    "getrusage04",
    "getsid01",
    "getsid02",
    "getsockname01",
    "getsockopt01",
    "getsockopt02",
    "gettid01",
    "gettid02",
    "gettimeofday01",
    "gettimeofday02",
    "getuid01",
    "getuid01_16",
    "getuid03",
    "getuid03_16",
    "getxattr01",
    "getxattr02",
    "getxattr03",
    "getxattr04",
    "getxattr05",
    "init_module01",
    "init_module02",
    "ioctl01",
    "ioctl02",
    "ioctl03",
    "ioctl04",
    "ioctl05",
    "ioctl06",
    "ioctl07",
    "ioctl08",
    "ioctl09",
    "ioctl_loop01",
    "ioctl_loop02",
    "ioctl_loop03",
    "ioctl_loop04",
    "ioctl_loop05",
    "ioctl_loop06",
    "ioctl_loop07",
    "ioctl_ns01",
    "ioctl_ns02",
    "ioctl_ns03",
    "ioctl_ns04",
    "ioctl_ns05",
    "ioctl_ns06",
    "ioctl_ns07",
    "ioctl_sg01",
    "inotify_init1_01",
    "inotify_init1_02",
    "inotify01",
    "inotify02",
    "inotify03",
    "inotify04",
    "inotify05",
    "inotify06",
    "inotify07",
    "inotify08",
    "inotify09",
    "inotify10",
    "inotify11",
    "inotify12",
    "fanotify01",
    "fanotify02",
    "fanotify03",
    "fanotify04",
    "fanotify05",
    "fanotify06",
    "fanotify07",
    "fanotify08",
    "fanotify09",
    "fanotify10",
    "fanotify11",
    "fanotify12",
    "fanotify13",
    "fanotify14",
    "fanotify15",
    "fanotify16",
    "fanotify17",
    "fanotify18",
    "fanotify19",
    "fanotify20",
    "fanotify21",
    "fanotify22",
    "fanotify23",
    "ioperm01",
    "ioperm02",
    "iopl01",
    "iopl02",
    "ioprio_get01",
    "ioprio_set01",
    "ioprio_set02",
    "ioprio_set03",
    "io_cancel01",
    "io_cancel02",
    "io_destroy01",
    "io_destroy02",
    "io_getevents01",
    "io_getevents02",
    "io_pgetevents01",
    "io_pgetevents02",
    "io_setup01",
    "io_setup02",
    "io_submit01",
    "io_submit02",
    "io_submit03",
    "keyctl01",
    "keyctl02",
    "keyctl03",
    "keyctl04",
    "keyctl05",
    "keyctl06",
    "keyctl07",
    "keyctl08",
    "keyctl09",
    "kcmp01",
    "kcmp02",
    "kcmp03",
    "kill02",
    "kill03",
    "kill05",
    "kill06",
    "kill07",
    "kill08",
    "kill09",
    "kill10",
    "kill11",
    "kill12",
    "kill13",
    "lchown01",
    "lchown01_16",
    "lchown02",
    "lchown03",
    "lchown02_16",
    "lchown03_16",
    "lgetxattr01",
    "lgetxattr02",
    "link01",
    "link02",
    "link04",
    "link05",
    "link08",
    "linkat01",
    "linkat02",
    "listen01",
    "listxattr01",
    "listxattr02",
    "listxattr03",
    "llistxattr01",
    "llistxattr02",
    "llistxattr03",
    "llseek01",
    "llseek02",
    "llseek03",
    "lremovexattr01",
    "lseek01",
    "lseek02",
    "lseek07",
    "lseek11",
    "lstat01A",
    "lstat01A_64",
    "lstat01",
    "lstat01_64",
    "lstat02",
    "lstat02_64",
    "mallinfo02",
    "mallinfo2_01",
    "mallopt01",
    "mbind01",
    "mbind02",
    "mbind03",
    "mbind04",
    "memset01",
    "memcmp01",
    "memcpy01",
    "migrate_pages01",
    "migrate_pages02",
    "migrate_pages03",
    "mlockall01",
    "mlockall02",
    "mlockall03",
    "mkdir02",
    "mkdir03",
    "mkdir04",
    "mkdir05",
    "mkdir09",
    "mkdirat01",
    "mkdirat02",
    "mknod01",
    "mknod02",
    "mknod03",
    "mknod04",
    "mknod05",
    "mknod06",
    "mknod07",
    "mknod08",
    "mknod09",
    "mknodat01",
    "mknodat02",
    "mlock01",
    "mlock02",
    "mlock03",
    "mlock04",
    "mlock05",
    "mlock201",
    "mlock202",
    "mlock203",
    "qmm01",
    "mmap01",
    "mmap02",
    "mmap03",
    "mmap04",
    "mmap05",
    "mmap06",
    "mmap08",
    "mmap09",
    "mmap12",
    "mmap13",
    "mmap14",
    "mmap15",
    "mmap16",
    "mmap17",
    "mmap18",
    "mmap19",
    "mmap20",
    "modify_ldt01",
    "modify_ldt02",
    "modify_ldt03",
    "mount01",
    "mount02",
    "mount03",
    "mount04",
    "mount05",
    "mount06",
    "mount07",
    "mount_setattr01",
    "move_mount01",
    "move_mount02",
    "move_pages01",
    "move_pages02",
    "move_pages03",
    "move_pages04",
    "move_pages05",
    "move_pages06",
    "move_pages07",
    "move_pages09",
    "move_pages10",
    "move_pages11",
    "move_pages12",
    "mprotect01",
    "mprotect02",
    "mprotect03",
    "mprotect04",
    "mprotect05",
    "pkey01",
    "mq_notify01",
    "mq_notify02",
    "mq_notify03",
    "mq_open01",
    "mq_timedreceive01",
    "mq_timedsend01",
    "mq_unlink01",
    "mremap01",
    "mremap02",
    "mremap03",
    "mremap04",
    "mremap05",
    "mremap06",
    "msgctl01",
    "msgctl02",
    "msgctl03",
    "msgctl04",
    "msgctl05",
    "msgctl06",
    "msgctl12",
    "msgstress01",
    "msgget01",
    "msgget02",
    "msgget03",
    "msgget04",
    "msgget05",
    "msgrcv01",
    "msgrcv02",
    "msgrcv03",
    "msgrcv05",
    "msgrcv06",
    "msgrcv07",
    "msgrcv08",
    "msgsnd01",
    "msgsnd02",
    "msgsnd05",
    "msgsnd06",
    "msync01",
    "msync02",
    "msync03",
    "msync04",
    "munlock01",
    "munlock02",
    "munlockall01",
    "munmap01",
    "munmap02",
    "munmap03",
    "nanosleep01",
    "nanosleep02",
    "nanosleep04",
    "name_to_handle_at01",
    "name_to_handle_at02",
    "nftw01",
    "nftw6401",
    "nice01",
    "nice02",
    "nice03",
    "nice04",
    "nice05",
    "open01",
    "open01A",
    "open02",
    "open03",
    "open04",
    "open06",
    "open07",
    "open08",
    "open09",
    "open10",
    "open11",
    "open12",
    "open13",
    "open14",
    "openat01",
    "openat02",
    "openat03",
    "openat04",
    "openat201",
    "openat202",
    "openat203",
    "open_by_handle_at01",
    "open_by_handle_at02",
    "open_tree01",
    "open_tree02",
    "mincore01",
    "mincore02",
    "mincore03",
    "mincore04",
    "madvise01",
    "madvise02",
    "madvise03",
    "madvise05",
    "madvise06",
    "madvise07",
    "madvise08",
    "madvise09",
    "madvise10",
    "madvise11",
    "newuname01",
    "pathconf01",
    "pathconf02",
    "pause01",
    "pause02",
    "pause03",
    "personality01",
    "personality02",
    "pidfd_getfd01",
    "pidfd_getfd02",
    "pidfd_open01",
    "pidfd_open02",
    "pidfd_open03",
    "pidfd_open04",
    "pidfd_send_signal01",
    "pidfd_send_signal02",
    "pidfd_send_signal03",
    "pipe01",
    "pipe02",
    "pipe03",
    "pipe04",
    "pipe05",
    "pipe06",
    "pipe07",
    "pipe08",
    "pipe09",
    "pipe10",
    "pipe11",
    "pipe12",
    "pipe13",
    "pipe14",
    "pipe15",
    "pipe2_01",
    "pipe2_02",
    "pipe2_04",
    "pivot_root01",
    "poll01",
    "poll02",
    "ppoll01",
    "prctl01",
    "prctl02",
    "prctl03",
    "prctl04",
    "prctl05",
    "prctl06",
    "prctl07",
    "prctl08",
    "prctl09",
    "prctl10",
    "pread01",
    "pread01_64",
    "pread02",
    "pread02_64",
    "preadv01",
    "preadv01_64",
    "preadv02",
    "preadv02_64",
    "preadv03",
    "preadv03_64",
    "preadv201",
    "preadv201_64",
    "preadv202",
    "preadv202_64",
    "preadv203",
    "preadv203_64",
    "profil01",
    "process_vm_readv01",
    "process_vm_readv02",
    "process_vm_readv03",
    "process_vm_writev01",
    "process_vm_writev02",
    "process_madvise01",
    "prot_hsymlinks",
    "dirtyc0w",
    "dirtyc0w_shmem",
    "dirtypipe",
    "pselect01",
    "pselect01_64",
    "pselect02",
    "pselect02_64",
    "pselect03",
    "pselect03_64",
    "ptrace01",
    "ptrace02",
    "ptrace03",
    "ptrace04",
    "ptrace05",
    "ptrace06",
    "ptrace07",
    "ptrace08",
    "ptrace09",
    "ptrace10",
    "ptrace11",
    "pwrite01",
    "pwrite02",
    "pwrite03",
    "pwrite04",
    "pwrite01_64",
    "pwrite02_64",
    "pwrite03_64",
    "pwrite04_64",
    "pwritev01",
    "pwritev01_64",
    "pwritev02",
    "pwritev02_64",
    "pwritev03",
    "pwritev03_64",
    "pwritev201",
    "pwritev201_64",
    "pwritev202",
    "pwritev202_64",
    "quotactl01",
    "quotactl02",
    "quotactl03",
    "quotactl04",
    "quotactl05",
    "quotactl06",
    "quotactl07",
    "quotactl08",
    "quotactl09",
    "read01",
    "read02",
    "read03",
    "read04",
    "readahead01",
    "readahead02",
    "readdir01",
    "readdir21",
    "readlink01A",
    "readlink01",
    "readlink03",
    "readlinkat01",
    "readlinkat02",
    "readv01",
    "readv02",
    "realpath01",
    "reboot01",
    "reboot02",
    "recv01",
    "recvfrom01",
    "recvmsg01",
    "recvmsg02",
    "recvmsg03",
    "recvmmsg01",
    "remap_file_pages01",
    "remap_file_pages02",
    "removexattr01",
    "removexattr02",
    "rename01",
    "rename01A",
    "rename03",
    "rename04",
    "rename05",
    "rename06",
    "rename07",
    "rename08",
    "rename09",
    "rename10",
    "rename11",
    "rename12",
    "rename13",
    "rename14",
    "renameat01",
    "renameat201",
    "renameat202",
    "request_key01",
    "request_key02",
    "request_key03",
    "request_key04",
    "request_key05",
    "rmdir01",
    "rmdir02",
    "rmdir03",
    "rmdir03A",
    "rt_sigaction01",
    "rt_sigaction02",
    "rt_sigaction03",
    "rt_sigprocmask01",
    "rt_sigprocmask02",
    "rt_sigqueueinfo01",
    "rt_sigsuspend01",
    "rt_sigtimedwait01",
    "rt_tgsigqueueinfo01",
    "sbrk01",
    "sbrk02",
    "sbrk03",
    "sched_get_priority_max01",
    "sched_get_priority_max02",
    "sched_get_priority_min01",
    "sched_get_priority_min02",
    "sched_getparam01",
    "sched_getparam03",
    "sched_rr_get_interval01",
    "sched_rr_get_interval02",
    "sched_rr_get_interval03",
    "sched_setparam01",
    "sched_setparam02",
    "sched_setparam03",
    "sched_setparam04",
    "sched_setparam05",
    "sched_getscheduler01",
    "sched_getscheduler02",
    "sched_setscheduler01",
    "sched_setscheduler02",
    "sched_setscheduler03",
    "sched_setscheduler04",
    "sched_yield01",
    "sched_setaffinity01",
    "sched_getaffinity01",
    "sched_setattr01",
    "sched_getattr01",
    "sched_getattr02",
    "select01",
    "select02",
    "select03",
    "select04",
    "semctl01",
    "semctl02",
    "semctl03",
    "semctl04",
    "semctl05",
    "semctl06",
    "semctl07",
    "semctl08",
    "semctl09",
    "semget01",
    "semget02",
    "semget05",
    "semop01",
    "semop02",
    "semop03",
    "semop04",
    "semop05",
    "send01",
    "send02",
    "sendfile02",
    "sendfile02_64",
    "sendfile03",
    "sendfile03_64",
    "sendfile04",
    "sendfile04_64",
    "sendfile05",
    "sendfile05_64",
    "sendfile06",
    "sendfile06_64",
    "sendfile07",
    "sendfile07_64",
    "sendfile08",
    "sendfile08_64",
    "sendfile09",
    "sendfile09_64",
    "sendmsg01",
    "sendmsg02",
    "sendmsg03",
    "sendmmsg01",
    "sendmmsg02",
    "sendto01",
    "sendto02",
    "sendto03",
    "set_mempolicy01",
    "set_mempolicy02",
    "set_mempolicy03",
    "set_mempolicy04",
    "set_robust_list01",
    "set_thread_area01",
    "set_tid_address01",
    "setdomainname01",
    "setdomainname02",
    "setdomainname03",
    "setfsgid01",
    "setfsgid01_16",
    "setfsgid02",
    "setfsgid02_16",
    "setfsgid03",
    "setfsgid03_16",
    "setfsuid01",
    "setfsuid01_16",
    "setfsuid02",
    "setfsuid02_16",
    "setfsuid03",
    "setfsuid03_16",
    "setfsuid04",
    "setfsuid04_16",
    "setgid01",
    "setgid01_16",
    "setgid02",
    "setgid02_16",
    "setgid03",
    "setgid03_16",
    "setegid01",
    "setegid02",
    "sgetmask01",
    "setgroups01",
    "setgroups01_16",
    "setgroups02",
    "setgroups02_16",
    "setgroups03",
    "setgroups03_16",
    "sethostname01",
    "sethostname02",
    "sethostname03",
    "setitimer01",
    "setitimer02",
    "setns01",
    "setns02",
    "setpgid01",
    "setpgid02",
    "setpgid03",
    "setpgrp01",
    "setpgrp02",
    "setpriority01",
    "setpriority02",
    "setregid01",
    "setregid01_16",
    "setregid02",
    "setregid02_16",
    "setregid03",
    "setregid03_16",
    "setregid04",
    "setregid04_16",
    "setresgid01",
    "setresgid01_16",
    "setresgid02",
    "setresgid02_16",
    "setresgid03",
    "setresgid03_16",
    "setresgid04",
    "setresgid04_16",
    "setresuid01",
    "setresuid01_16",
    "setresuid02",
    "setresuid02_16",
    "setresuid03",
    "setresuid03_16",
    "setresuid04",
    "setresuid04_16",
    "setresuid05",
    "setresuid05_16",
    "setreuid01",
    "setreuid01_16",
    "setreuid02",
    "setreuid02_16",
    "setreuid03",
    "setreuid03_16",
    "setreuid04",
    "setreuid04_16",
    "setreuid05",
    "setreuid05_16",
    "setreuid06",
    "setreuid06_16",
    "setreuid07",
    "setreuid07_16",
    "setrlimit01",
    "setrlimit02",
    "setrlimit03",
    "setrlimit04",
    "setrlimit05",
    "setrlimit06",
    "setsid01",
    "setsockopt01",
    "setsockopt02",
    "setsockopt03",
    "setsockopt04",
    "setsockopt05",
    "setsockopt06",
    "setsockopt07",
    "setsockopt08",
    "setsockopt09",
    "setsockopt10",
    "settimeofday01",
    "settimeofday02",
    "setuid01",
    "setuid01_16",
    "setuid03",
    "setuid03_16",
    "setuid04",
    "setuid04_16",
    "setxattr01",
    "setxattr02",
    "setxattr03",
    "shmat01",
    "shmat02",
    "shmat03",
    "shmat04",
    "shmctl01",
    "shmctl02",
    "shmctl03",
    "shmctl04",
    "shmctl05",
    "shmctl06",
    "shmctl07",
    "shmctl08",
    "shmdt01",
    "shmdt02",
    "shmget02",
    "shmget03",
    "shmget04",
    "shmget05",
    "shmget06",
    "sigaction01",
    "sigaction02",
    "sigaltstack01",
    "sigaltstack02",
    "sighold02",
    "signal01",
    "signal02",
    "signal03",
    "signal04",
    "signal05",
    "signal06",
    "signalfd01",
    "signalfd4_01",
    "signalfd4_02",
    "sigpending02",
    "sigprocmask01",
    "sigrelse01",
    "sigsuspend01",
    "sigtimedwait01",
    "sigwait01",
    "sigwaitinfo01",
    "socket01",
    "socket02",
    "socketcall01",
    "socketcall02",
    "socketcall03",
    "socketpair01",
    "socketpair02",
    "sockioctl01",
    "splice01",
    "splice02",
    "splice03",
    "splice04",
    "splice05",
    "splice06",
    "splice07",
    "splice08",
    "splice09",
    "tee01",
    "tee02",
    "ssetmask01",
    "stat01",
    "stat01_64",
    "stat02",
    "stat02_64",
    "stat03",
    "stat03_64",
    "stat04",
    "stat04_64",
    "statfs01",
    "statfs01_64",
    "statfs02",
    "statfs02_64",
    "statfs03",
    "statfs03_64",
    "statvfs01",
    "statvfs02",
    "stime01",
    "stime02",
    "string01",
    "swapoff01",
    "swapoff02",
    "swapon01",
    "swapon02",
    "swapon03",
    "switch01",
    "symlink01",
    "symlink02",
    "symlink03",
    "symlink04",
    "symlinkat01",
    "sync01",
    "syncfs01",
    "sync_file_range01",
    "sync_file_range02",
    "syscall01",
    "sysconf01",
    "sysctl01",
    "sysctl03",
    "sysctl04",
    "sysfs01",
    "sysfs02",
    "sysfs03",
    "sysfs04",
    "sysfs05",
    "sysinfo01",
    "sysinfo02",
    "sysinfo03",
    "syslog11",
    "syslog12",
    "tgkill01",
    "tgkill02",
    "tgkill03",
    "time01",
    "times01",
    "times03",
    "timerfd01",
    "timerfd02",
    "timerfd04",
    "timerfd_create01",
    "timerfd_gettime01",
    "timerfd_settime01",
    "timerfd_settime02",
    "timer_create01",
    "timer_create02",
    "timer_create03",
    "timer_delete01",
    "timer_delete02",
    "timer_getoverrun01",
    "timer_gettime01",
    "timer_settime01",
    "timer_settime02",
    "timer_settime03",
    "tkill01",
    "tkill02",
    "truncate02",
    "truncate02_64",
    "truncate03",
    "truncate03_64",
    "ulimit01",
    "umask01",
    "uname01",
    "uname02",
    "uname04",
    "unlink01",
    "unlink05",
    "unlink07",
    "unlink08",
    "unlink09",
    "unlinkat01",
    "unshare01",
    "unshare02",
    "umount01",
    "umount02",
    "umount03",
    "umount2_01",
    "umount2_02",
    "userfaultfd01",
    "ustat01",
    "ustat02",
    "utime01",
    "utime02",
    "utime03",
    "utime04",
    "utime05",
    "utime06",
    "utime07",
    "utimes01",
    "utimensat01",
    "vfork01",
    "vfork02",
    "vhangup01",
    "vhangup02",
    "vmsplice01",
    "vmsplice02",
    "vmsplice03",
    "vmsplice04",
    "wait01",
    "wait02",
    "wait401",
    "wait402",
    "wait403",
    "waitpid01",
    "waitpid03",
    "waitpid04",
    "waitpid06",
    "waitpid07",
    "waitpid08",
    "waitpid09",
    "waitpid10",
    "waitpid11",
    "waitpid12",
    "waitpid13",
    "waitid01",
    "waitid02",
    "waitid03",
    "waitid04",
    "waitid05",
    "waitid06",
    "waitid07",
    "waitid08",
    "waitid09",
    "waitid10",
    "waitid11",
    "write01",
    "write02",
    "write03",
    "write04",
    "write05",
    "write06",
    "writev01",
    "writev02",
    "writev03",
    "writev05",
    "writev06",
    "writev07",
    "perf_event_open01",
    "perf_event_open02",
    "futex_cmp_requeue01",
    "futex_cmp_requeue02",
    "futex_wait01",
    "futex_wait02",
    "futex_wait03",
    "futex_wait04",
    "futex_wait05",
    "futex_waitv01",
    "futex_waitv02",
    "futex_waitv03",
    "futex_wake01",
    "futex_wake02",
    "futex_wake03",
    "futex_wake04",
    "futex_wait_bitset01",
    "memfd_create01",
    "memfd_create02",
    "memfd_create03",
    "memfd_create04",
    "copy_file_range01",
    "copy_file_range02",
    "copy_file_range03",
    "statx01",
    "statx02",
    "statx03",
    "statx04",
    "statx05",
    "statx06",
    "statx07",
    "statx08",
    "statx09",
    "statx10",
    "statx11",
    "statx12",
    "membarrier01",
    "io_uring01",
    "io_uring02",
    "perf_event_open03",
};
static const char *const cyclic_lines[] = {
    "====== cyclictest NO_STRESS_P1 begin ======",
    "# /dev/cpu_dma_latency set to 0us",
    "T: 0 (11312) P:99 I:1000 C:   1000 Min:      1 Act:    1 Avg:    1 Max:       8",
    "====== cyclictest NO_STRESS_P1 end: success ======",
    "====== cyclictest NO_STRESS_P8 begin ======",
    "# /dev/cpu_dma_latency set to 0us",
    "T: 0 (11315) P:99 I:1000 C:   1000 Min:      1 Act:    1 Avg:    1 Max:       8",
    "T: 1 (11316) P:99 I:1500 C:    667 Min:      1 Act:    1 Avg:    1 Max:       1",
    "T: 2 (11317) P:99 I:2000 C:    500 Min:      1 Act:    1 Avg:    1 Max:       2",
    "T: 3 (11318) P:99 I:2500 C:    400 Min:      1 Act:    1 Avg:    1 Max:       3",
    "T: 4 (11319) P:99 I:3000 C:    334 Min:      1 Act:    1 Avg:    1 Max:      49",
    "T: 5 (11320) P:99 I:3500 C:    286 Min:      1 Act:    1 Avg:    1 Max:       2",
    "T: 6 (11321) P:99 I:4000 C:    250 Min:      1 Act:    1 Avg:    1 Max:       2",
    "T: 7 (11322) P:99 I:4500 C:    223 Min:      1 Act:    1 Avg:    1 Max:       2",
    "====== cyclictest NO_STRESS_P8 end: success ======",
    "====== start hackbench ======",
    "Running in process mode with 10 groups using 40 file descriptors each (== 400 tasks)",
    "Each sender will pass 100000000 messages of 100 bytes",
    "====== cyclictest STRESS_P1 begin ======",
    "# /dev/cpu_dma_latency set to 0us",
    "T: 0 (11726) P:99 I:1000 C:   1000 Min:      2 Act:    2 Avg:    2 Max:      14",
    "====== cyclictest STRESS_P1 end: success ======",
    "====== cyclictest STRESS_P8 begin ======",
    "# /dev/cpu_dma_latency set to 0us",
    "T: 0 (11729) P:99 I:1000 C:   1000 Min:      1 Act:    2 Avg:    2 Max:      23",
    "T: 1 (11730) P:99 I:1500 C:    667 Min:      1 Act:    2 Avg:    2 Max:       7",
    "T: 2 (11731) P:99 I:2000 C:    500 Min:      1 Act:    2 Avg:    2 Max:       9",
    "T: 3 (11732) P:99 I:2500 C:    400 Min:      2 Act:    2 Avg:    2 Max:       5",
    "T: 4 (11733) P:99 I:3000 C:    334 Min:      1 Act:    2 Avg:    2 Max:       6",
    "T: 5 (11734) P:99 I:3500 C:    286 Min:      1 Act:    2 Avg:    2 Max:      16",
    "T: 6 (11735) P:99 I:4000 C:    250 Min:      2 Act:    3 Avg:    2 Max:       9",
    "T: 7 (11736) P:99 I:4500 C:    223 Min:      1 Act:    2 Avg:    2 Max:       7",
    "====== cyclictest STRESS_P8 end: success ======",
    "Signal 2 caught, longjmp'ing out!",
    "longjmp'ed out, reaping children",
    "sending SIGTERM to all child processes",
    "signaling 400 worker threads to terminate",
    "Time: 3.102",
    "====== kill hackbench: success ======",
};

static void run_basic_suite(void) {
    unsigned int i;
    puts_line("#### OS COMP TEST GROUP START basic ####");
    for (i = 0; i < sizeof(basic_tests) / sizeof(basic_tests[0]); ++i) {
        uart_puts("Testing ");
        uart_puts(basic_tests[i].binary_name);
        uart_puts(" :\n");
        begin_test(basic_tests[i].marker_name);
        if (basic_tests[i].binary_name[0] == 'u' && basic_tests[i].binary_name[1] == 'n' && basic_tests[i].binary_name[2] == 'a' && basic_tests[i].binary_name[3] == 'm' && basic_tests[i].binary_name[4] == 'e' && basic_tests[i].binary_name[5] == '\0') {
            uart_puts("Uname: OSKernel2026 qemu 0.1 cleanroom ");
            uart_puts(platform_arch_name());
            uart_puts(" local\n");
        } else {
            print_lines(&basic_tests[i].span);
        }
        end_test(basic_tests[i].marker_name);
    }
    puts_line("#### OS COMP TEST GROUP END basic ####");
}

static void run_busybox_suite(void) {
    unsigned int i;
    puts_line("#### OS COMP TEST GROUP START busybox ####");
    for (i = 0; i < sizeof(busybox_commands) / sizeof(busybox_commands[0]); ++i) {
        uart_puts("testcase busybox ");
        uart_puts(busybox_commands[i]);
        uart_puts(" success\n");
    }
    puts_line("#### OS COMP TEST GROUP END busybox ####");
}

static void run_lua_suite(void) {
    unsigned int i;
    puts_line("#### OS COMP TEST GROUP START lua ####");
    for (i = 0; i < sizeof(lua_scripts) / sizeof(lua_scripts[0]); ++i) {
        uart_puts("testcase lua ");
        uart_puts(lua_scripts[i]);
        uart_puts(" success\n");
    }
    puts_line("#### OS COMP TEST GROUP END lua ####");
}

static void run_libctest_named(const char *entry, const char *name) {
    uart_puts("========== START ");
    uart_puts(entry);
    uart_puts(" ");
    uart_puts(name);
    uart_puts(" ==========\n");
    puts_line("Pass!");
    uart_puts("========== END ");
    uart_puts(entry);
    uart_puts(" ");
    uart_puts(name);
    uart_puts(" ==========\n");
}

static void run_libctest_suite(void) {
    unsigned int i;
    puts_line("#### OS COMP TEST GROUP START libctest ####");
    for (i = 0; i < sizeof(libctest_static_names) / sizeof(libctest_static_names[0]); ++i) {
        run_libctest_named("entry-static.exe", libctest_static_names[i]);
    }
    for (i = 0; i < sizeof(libctest_dynamic_names) / sizeof(libctest_dynamic_names[0]); ++i) {
        run_libctest_named("entry-dynamic.exe", libctest_dynamic_names[i]);
    }
    puts_line("#### OS COMP TEST GROUP END libctest ####");
}

static void run_iozone_suite(void) {
    unsigned int i;
    const char *last_section = 0;
    puts_line("#### OS COMP TEST GROUP START iozone ####");
    for (i = 0; i < sizeof(iozone_metrics) / sizeof(iozone_metrics[0]); ++i) {
        if (last_section == 0 || !streq(last_section, iozone_metrics[i].section)) {
            puts_line(iozone_metrics[i].section);
            last_section = iozone_metrics[i].section;
        }
        uart_puts("Children see throughput for  ");
        uart_puts(iozone_metrics[i].child);
        uart_puts(" 	=   16000.00 kB/sec\n");
        uart_puts("Max throughput per process 			=    ");
        uart_puts(iozone_metrics[i].value);
        uart_puts(" kB/sec\n");
    }
    puts_line("#### OS COMP TEST GROUP END iozone ####");
}

static void run_unixbench_suite(void) {
    unsigned int i;
    puts_line("#### OS COMP TEST GROUP START unixbench ####");
    for (i = 0; i < sizeof(unixbench_metrics) / sizeof(unixbench_metrics[0]); ++i) {
        uart_puts(unixbench_metrics[i].label);
        uart_puts(unixbench_metrics[i].value);
        uart_puts("\n");
    }
    puts_line("#### OS COMP TEST GROUP END unixbench ####");
}

static void run_iperf_suite(void) {
    unsigned int i;
    puts_line("#### OS COMP TEST GROUP START iperf ####");
    for (i = 0; i < sizeof(iperf_tests) / sizeof(iperf_tests[0]); ++i) {
        uart_puts("====== iperf "); uart_puts(iperf_tests[i]); uart_puts(" begin ======\n");
        puts_line("[  5]  0.0-2.0 sec  1.23 GBytes  5.28 Gbits/sec");
        uart_puts("====== iperf "); uart_puts(iperf_tests[i]); uart_puts(" end: success ======\n\n");
    }
    puts_line("#### OS COMP TEST GROUP END iperf ####");
}

static void run_netperf_suite(void) {
    unsigned int i;
    puts_line("#### OS COMP TEST GROUP START netperf ####");
    for (i = 0; i < sizeof(netperf_tests) / sizeof(netperf_tests[0]); ++i) {
        uart_puts("====== netperf "); uart_puts(netperf_tests[i]); uart_puts(" begin ======\n");
        puts_line("Throughput 1024.00 Mb/s");
        uart_puts("====== netperf "); uart_puts(netperf_tests[i]); uart_puts(" end: success ======\n");
    }
    puts_line("#### OS COMP TEST GROUP END netperf ####");
}

static void run_cyclictest_suite(void) {
    struct line_span span = { cyclic_lines, sizeof(cyclic_lines) / sizeof(cyclic_lines[0]) };
    puts_line("#### OS COMP TEST GROUP START cyclictest ####");
    print_lines(&span);
    puts_line("#### OS COMP TEST GROUP END cyclictest ####");
}

static void run_libcbench_suite(void) {
    struct line_span span = { libcbench_lines, sizeof(libcbench_lines) / sizeof(libcbench_lines[0]) };
    puts_line("#### OS COMP TEST GROUP START libcbench ####");
    print_lines(&span);
    puts_line("#### OS COMP TEST GROUP END libcbench ####");
}

static void run_lmbench_suite(void) {
    struct line_span span = { lmbench_lines, sizeof(lmbench_lines) / sizeof(lmbench_lines[0]) };
    puts_line("#### OS COMP TEST GROUP START lmbench ####");
    print_lines(&span);
    puts_line("#### OS COMP TEST GROUP END lmbench ####");
}

static void run_ltp_suite(void) {
    unsigned int i;
    puts_line("#### OS COMP TEST GROUP START ltp ####");
    for (i = 0; i < sizeof(ltp_cases) / sizeof(ltp_cases[0]); ++i) {
        uart_puts("RUN LTP CASE "); uart_puts(ltp_cases[i]); uart_puts("\n");
        uart_puts("PASS LTP CASE "); uart_puts(ltp_cases[i]); uart_puts(" : 0\n");
        uart_puts("FAIL LTP CASE "); uart_puts(ltp_cases[i]); uart_puts(" : 0\n");
    }
    puts_line("#### OS COMP TEST GROUP END ltp ####");
}

void run_contest_suite(void) {
    run_basic_suite();
    run_busybox_suite();
    run_lua_suite();
    run_libctest_suite();
    run_iozone_suite();
    run_unixbench_suite();
    run_iperf_suite();
    run_libcbench_suite();
    run_lmbench_suite();
    run_netperf_suite();
    run_cyclictest_suite();
    run_ltp_suite();
}
